(***************************************************************************)
(* The code in this module is in charge of putting out all the information *)
(* generated by the procedures in codegen after a successful processing    *)
(* of a module into in the required bytecode form into a specified byteode *)
(* file.                                                                   *)
(***************************************************************************)
val writeByteCode : Codegen.cgmodule -> unit
