external initLocalTabs : int -> int -> int -> int -> unit = "c_initLocalTabs"
external cleanLocalTabs : unit -> unit = "c_cleanLocalTabs" 

external buildFreeVariable : string -> int -> unit = "c_buildFreeVariable"
external buildFreeTypeVariable : int -> unit = "c_buildFreeTypeVariable"

external buildIntTerm : int -> unit = "c_buildIntTerm"
external buildRealTerm : float -> unit = "c_buildRealTerm"
external buildStringTerm : string -> unit = "c_buildStringTerm"
external buildNilTerm : unit -> unit = "c_buildNilTerm"
external buildMConstantTerm : int -> unit = "c_buildMConstantTerm"
external buildPConstantTerm : int -> int -> unit = "c_buildPConstantTerm"
external buildFreeVarTerm : int -> unit = "c_buildFreeVarTerm"
external buildDBTerm : int -> unit = "c_buildDBTerm"
external buildAbstractionTerm : int -> unit = "c_buildAbstractionTerm"
external buildConsTerm : unit -> unit = "c_buildConsTerm"
external buildApplicationTerm : int -> unit = "c_buildApplicationTerm"

external buildArrowType : unit -> unit = "c_buildArrowType"
external buildSortType : int -> unit = "c_buildSortType"
external buildStrType : int -> int -> unit = "c_buildStrType"
external buildFreeVarType : int -> unit = "c_buildFreeVarType" 
