/****************************************************************************/
/* Teyjus, an implementation of Lambda Prolog                               */
/* Copyright (C) 1999 Gopalan Nadathur                                      */
/*                                                                          */
/* This program is free software; you can redistribute it and/or modify     */
/* it under the terms of the GNU General Public License as published by     */
/* the Free Software Foundation; either version 2 of the License, or        */
/* (at your option) any later version.                                      */
/*                                                                          */
/* This program is distributed in the hope that it will be useful,          */
/* but WITHOUT ANY WARRANTY; without even the implied warranty of           */
/* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            */
/* GNU General Public License for more details.                             */
/*                                                                          */
/* You should have received a copy of the GNU General Public License        */
/* along with this program; if not, write to the Free Software              */
/* Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA */
/****************************************************************************/
/****************************************************************************/
/*                                                                          */
/*                                Teyjus, 1996                              */
/*                                                                          */
/*   File instructions.c. This file fills out an array of information for   */
/*   each instruction in the repertoire of the machine.                     */
/*                                                                          */
/****************************************************************************/

#include <config.h>
#include "instructions.h"

struct INSTR_info_ty INSTR_info[NUM_INSTRUCTIONS] = {
{ "unify_nil",                     P_P_P_L,          P_P_P_L_Len},
{ "get_list",                      R_P_P_L,          R_P_P_L_Len},
{ "put_nil",                       R_P_P,            R_P_P_Len},
{ "unify_variable_t",              R_P_P,            R_P_P_Len},
{ "unify_variable_tty",            R_I1_P,           R_I1_P_Len},
{ "unify_value_t",                 R_I1_P,           R_I1_P_Len},
{ "unify_value_p",                 E_I1_P,           E_I1_P_Len},
{ "unify_l_value_t",               R_I1_P,           R_I1_P_Len},
{ "unify_l_value_p",               E_I1_P,           E_I1_P_Len},
{ "globalize_t",                   R_P_P,            R_P_P_Len},
{ "globalize_pt",                  E_R_P,            E_R_P_Len},
{ "deref",                         R_P_P,            R_P_P_Len},
{ "set_value_t",                   R_P_P,            R_P_P_Len},
{ "set_value_p",                   E_P_P,            E_P_P_Len},
{ "copy_value",                    E_R_P,            E_R_P_Len},
{ "head_normalize_t",              R_P_P,            R_P_P_Len},
{ "head_normalize_p",              E_P_P,            E_P_P_Len},
{ "get_variable_t",                R_R_P,            R_R_P_Len},
{ "get_variable_p",                E_R_P,            E_R_P_Len},
{ "put_value_t",                   R_R_P,            R_R_P_Len},
{ "put_value_p",                   E_R_P,            E_R_P_Len},
{ "put_clambda",                   R_R_P,            R_R_P_Len},
{ "put_flambda",                   R_R_P,            R_R_P_Len},

{ "put_unsafe_value",              E_R_P,            E_R_P_Len},

{ "init_variable_t",               R_CE_P,           R_CE_P_Len},
{ "init_variable_p",               E_CE_P,           E_CE_P_Len},
{ "put_capp",                      R_R_I1,           R_R_I1_Len},
{ "put_fapp",                      R_R_I1,           R_R_I1_Len},
{ "put_clist",                     R_P_P,            R_P_P_Len},
{ "put_flist",                     R_P_P,            R_P_P_Len},
{ "set_clambda",                   R_P_P,            R_P_P_Len},
{ "set_flambda",                   R_P_P,            R_P_P_Len},
{ "unify_m_constant",              P_C,              P_C_Len},
{ "get_m_constant",                R_C,              R_C_Len},
{ "put_p_const",                   R_C,              R_C_Len},
{ "put_m_const",                   R_C,              R_C_Len},
{ "set_p_constant",                P_C,              P_C_Len},
{ "set_m_constant",                P_C,              P_C_Len},
{ "set_nil",                       P_P_P,            P_P_P_Len},
{ "unify_m_variable_t",            R_T,              R_T_Len},
{ "unify_m_variable_p",            E_T,              E_T_Len},
{ "set_p_variable_t",              R_T_I1_P_P_P,     R_T_I1_P_P_P_Len},
{ "set_p_variable_p",              E_T_I1_P_P_P,     E_T_I1_P_P_P_Len},
{ "set_m_variable_t",              R_T,              R_T_Len},
{ "set_m_variable_p",              E_T,              E_T_Len},
{ "get_p_structure",               R_C_I1_P_P_P_L,   R_C_I1_P_P_P_L_Len},
{ "get_m_structure",               R_C_I1_P_P_P,     R_C_I1_P_P_P_Len},
{ "put_p_variable_t",              R_T_R_I1_P_P,     R_T_R_I1_P_P_Len},
{ "put_p_variable_p",              E_T_R_I1_P_P,     E_T_R_I1_P_P_Len},
{ "put_m_variable_t",              R_T_R_P_P_P,      R_T_R_P_P_P_Len},
{ "put_m_variable_p",              E_T_R_P_P_P,      E_T_R_P_P_P_Len},
{ "get_nil",                       R_P_P_L,          R_P_P_L_Len},
{ "unify_void",                    I1_P_P_L,         I1_P_P_L_Len},
{ "put_index",                     R_I1_P,           R_I1_P_Len},
{ "set_index",                     I1_P_P,           I1_P_P_Len},
{ "put_cheavylambda",              R_R_P_S,          R_R_P_S_Len},
{ "put_fheavylambda",              R_R_P_S,          R_R_P_S_Len},
{ "unify_p_constant",              P_C_L,            P_C_L_Len},
{ "get_p_constant",                R_C_L,            R_C_L_Len},
{ "unify_p_variable_t",            R_T_L,            R_T_L_Len},
{ "unify_p_variable_p",            E_T_L,            E_T_L_Len},
{ "unify_type_variable_t",         R_P_P,            R_P_P_Len},
{ "unify_type_variable_p",         E_P_P,            E_P_P_Len},
{ "unify_type_value_t",            R_P_P,            R_P_P_Len},
{ "unify_envty_value_t",           R_P_P,            R_P_P_Len},
{ "unify_type_value_p",            E_P_P,            E_P_P_Len},
{ "unify_envty_value_p",           E_P_P,            E_P_P_Len},
{ "unified_type_value_t",          R_P_P,            R_P_P_Len},
{ "unified_type_value_p",          E_P_P,            E_P_P_Len},
{ "unify_type_l_value_t",          R_P_P,            R_P_P_Len},
{ "unify_envty_l_value_t",         R_P_P,            R_P_P_Len},
{ "unify_type_l_value_p",          E_P_P,            E_P_P_Len},
{ "unify_envty_l_value_p",         E_P_P,            E_P_P_Len},
{ "unified_type_l_value_t",        R_P_P,            R_P_P_Len},
{ "unified_type_l_value_p",        E_P_P,            E_P_P_Len},
{ "set_type_variable_t",           R_P_P,            R_P_P_Len},
{ "set_type_variable_p",           E_P_P,            E_P_P_Len},
{ "set_type_value_t",              R_P_P,            R_P_P_Len},
{ "set_type_value_p",              E_P_P,            E_P_P_Len},
{ "set_type_l_value_t",            R_P_P,            R_P_P_Len},
{ "set_type_l_value_p",            E_P_P,            E_P_P_Len},
{ "get_type_variable_t",           R_R_P,            R_R_P_Len},
{ "get_type_variable_p",           E_R_P,            E_R_P_Len},
{ "get_type_value_t",              R_R_P,            R_R_P_Len},
{ "get_type_value_p",              E_R_P,            E_R_P_Len},
{ "put_type_variable_t",           R_R_P,            R_R_P_Len},
{ "put_type_variable_p",           E_R_P,            E_R_P_Len},
{ "put_type_value_t",              R_R_P,            R_R_P_Len},
{ "put_type_value_p",              E_R_P,            E_R_P_Len},
{ "put_type_unsafe_value",         E_R_P,            E_R_P_Len},
{ "get_type_arrow",                R_R_R_I1_P_P_P,   R_R_R_I1_P_P_P_Len},
{ "put_type_arrow",                R_R_I1,           R_R_I1_Len},
{ "unify_argty_variable_t",        R_R_R,            R_R_R_Len},
{ "unify_argty_variable_p",        E_R_R,            E_R_R_Len},
{ "unify_argty_value_t",           R_R_R,            R_R_R_Len},
{ "unify_argty_value_p",           E_R_R,            E_R_R_Len},
{ "unify_argty_l_value_t",         R_R_R,            R_R_R_Len},
{ "unify_argty_l_value_p",         E_R_R,            E_R_R_Len},
{ "unify_targty_variable_t",       R_R_R,            R_R_R_Len},
{ "unify_targty_variable_p",       E_R_R,            E_R_R_Len},
{ "unify_targty_value_t",          R_R_R,            R_R_R_Len},
{ "unify_targty_value_p",          E_R_R,            E_R_R_Len},
{ "unify_targty_l_value_t",        R_R_R,            R_R_R_Len},
{ "unify_targty_l_value_p",        E_R_R,            E_R_R_Len},
{ "unify_type_constant",           P_K,              P_K_Len},
{ "set_type_constant",             P_K,              P_K_Len},
{ "get_type_constant",             R_K,              R_K_Len},
{ "get_type_structure",            R_K,              R_K_Len},
{ "put_type_const",                R_K,              R_K_Len},
{ "put_type_structure",            R_K,              R_K_Len},
{ "unify_argty_constant",          R_K_R_P_P_P,      R_K_R_P_P_P_Len},
{ "unify_targty_constant",         R_K_R_P_P_P,      R_K_R_P_P_P_Len},

{ "call_finish_unify",             I1_I1_P,          I1_I1_P_Len},
{ "execute_finish_unify",          I1_P_P,           I1_P_P_Len},
{ "proceed_finish_unify",          P_P_P,            P_P_P_Len},
{ "simpl_t",                       R_R_P,            R_R_P_Len},
{ "simpl_p",                       E_R_P,            E_R_P_Len},


{ "incr_universe",                 P_P_P,            P_P_P_Len},
{ "decr_universe",                 P_P_P,            P_P_P_Len},
{ "pop_impl_point",                P_P_P,             P_P_P_Len},
{ "pop_imports",                   I1_P_P,           I1_P_P_Len},
{ "set_univ_tag_p",                E_C,              E_C_Len},
{ "set_univ_tag_m",                E_C,              E_C_Len},
{ "tag_p_exists_t",                R_T_I1_P_P_P,     R_T_I1_P_P_P_Len},
{ "tag_p_exists_p",                E_T_I1_P_P_P,     E_T_I1_P_P_P_Len},
{ "tag_m_exists_t",                R_T,              R_T_Len},
{ "tag_m_exists_p",                E_T,              E_T_Len},
{ "tag_p_variable",                E_T_I1_P_P_P,     E_T_I1_P_P_P_Len},
{ "tag_m_variable",                E_T,              E_T_Len},
{ "push_import",                   P_P_P_MT,         P_P_P_MT_Len},
{ "push_impl_point",               I1_P_P_IT,        I1_P_P_IT_Len},
{ "remove_imports",                I1_P_P_L,         I1_P_P_L_Len},
{ "add_imports",                   P_I1_I1_L,        P_I1_I1_L_Len},

{ "allocate",                      I1_P_P,           I1_P_P_Len},
{ "deallocate",                    P_P_P,            P_P_P_Len},
{ "proceed",                       P_P_P,            P_P_P_Len},
{ "execute_name",                  P_C,              P_C_Len},
{ "call_name",                     I1_C_P_P_P_P,     I1_C_P_P_P_P_Len},
{ "execute",                       P_P_P_L,          P_P_P_L_Len},
{ "call",                          I1_P_P_L,         I1_P_P_L_Len},

{ "trust_me",                      I1_P_P,           I1_P_P_Len},
{ "unify_backtrack",               P_P_P,            P_P_P_Len},
{ "trust_ext",                     I1_N_P,           I1_N_P_Len},
{ "retry_me_else",                 I1_P_P_L,         I1_P_P_L_Len},
{ "retry",                         I1_P_P_L,         I1_P_P_L_Len},
{ "trust",                         I1_P_P_L,         I1_P_P_L_Len},
{ "try_me_else",                   I1_P_P_L,         I1_P_P_L_Len},
{ "try",                           I1_P_P_L,         I1_P_P_L_Len},

{ "switch_on_constant",            I1_P_P_HT,        I1_P_P_HT_Len},
{ "switch_on_bvar",                I1_P_P_BVT,       I1_P_P_BVT_Len},
{ "switch_on_reg",                 N_P_P_L_L,        N_P_P_L_L_Len},
{ "switch_on_term",                P_P_P_L_L_L_L,    P_P_P_L_L_L_L_Len},

{ "neck_cut",                      P_P_P,            P_P_P_Len},
{ "get_level",                     E_P_P,            E_P_P_Len},
{ "put_level",                     E_P_P,            E_P_P_Len},
{ "cut",                           E_P_P,            E_P_P_Len},

{ "load_args_in_regs",             P_P_P,            P_P_P_Len},
{ "call_builtin",                  I1_I1_P_P_P_P_P,  I1_I1_P_P_P_P_P_Len},
{ "builtin",                       I1_P_P,           I1_P_P_Len},
{ "stop",                          P_P_P,            P_P_P_Len},
{ "halt",                          P_P_P,            P_P_P_Len},
{ "callp",                         P_P_P,            P_P_P_Len},
{ "fail",                          P_P_P,            P_P_P_Len},

{ "get_integer",                   R_P_P_I,          R_P_P_I_Len},
{ "get_float",                     R_P_P_F,          R_P_P_F_Len},
{ "get_string",                    R_P_P_SL,         R_P_P_SL_Len},
 
{ "unify_integer",                 P_P_P_I,          P_P_P_I_Len},
{ "unify_float",                   P_P_P_F,          P_P_P_F_Len},
{ "unify_string",                  P_P_P_SL,         P_P_P_SL_Len},
 
{ "put_integer",                   R_P_P_I,          R_P_P_I_Len},
{ "put_float",                     R_P_P_F,          R_P_P_F_Len},
{ "put_string",                    R_P_P_SL,         R_P_P_SL_Len},
 
{ "set_integer",                   P_P_P_I,          P_P_P_I_Len},
{ "set_float",                     P_P_P_F,          P_P_P_F_Len},
{ "set_string",                    P_P_P_SL,         P_P_P_SL_Len},

{ "init_type_variable_t",          R_CE_P,           R_CE_P_Len},
{ "init_type_variable_p",          R_CE_P,           R_CE_P_Len},
{ "set_p_variable_te",             R_T_I1_P_P_P,     R_T_I1_P_P_P_Len},
{ "set_m_variable_te",             R_T,              R_T_Len}
};


INSTR_operand_type
       INSTR_operand_types[NUM_INSTRUCTION_CATEGORIES][INSTR_MAX_OPERANDS] =
{
   {INSTR_P, INSTR_P, INSTR_P, INSTR_X, INSTR_X, INSTR_X, INSTR_X, INSTR_X },
   {INSTR_R, INSTR_P, INSTR_P, INSTR_X, INSTR_X, INSTR_X, INSTR_X, INSTR_X },
   {INSTR_E, INSTR_P, INSTR_P, INSTR_X, INSTR_X, INSTR_X, INSTR_X, INSTR_X },
   {INSTR_I1, INSTR_P, INSTR_P, INSTR_X, INSTR_X, INSTR_X, INSTR_X, INSTR_X },
   {INSTR_R, INSTR_R, INSTR_P, INSTR_X, INSTR_X, INSTR_X, INSTR_X, INSTR_X },
   {INSTR_E, INSTR_R, INSTR_P, INSTR_X, INSTR_X, INSTR_X, INSTR_X, INSTR_X },
   {INSTR_R, INSTR_CE, INSTR_P, INSTR_X, INSTR_X, INSTR_X, INSTR_X, INSTR_X },
   {INSTR_E, INSTR_CE, INSTR_P, INSTR_X, INSTR_X, INSTR_X, INSTR_X, INSTR_X },
   {INSTR_P, INSTR_C, INSTR_X, INSTR_X, INSTR_X, INSTR_X, INSTR_X, INSTR_X },
   {INSTR_P, INSTR_K, INSTR_X, INSTR_X, INSTR_X, INSTR_X, INSTR_X, INSTR_X },
   {INSTR_R, INSTR_R, INSTR_R, INSTR_X, INSTR_X, INSTR_X, INSTR_X, INSTR_X },
   {INSTR_E, INSTR_R, INSTR_R, INSTR_X, INSTR_X, INSTR_X, INSTR_X, INSTR_X },
   {INSTR_R, INSTR_C, INSTR_X, INSTR_X, INSTR_X, INSTR_X, INSTR_X, INSTR_X },
   {INSTR_E, INSTR_C, INSTR_X, INSTR_X, INSTR_X, INSTR_X, INSTR_X, INSTR_X },
   {INSTR_R, INSTR_T, INSTR_X, INSTR_X, INSTR_X, INSTR_X, INSTR_X, INSTR_X },
   {INSTR_E, INSTR_T, INSTR_X, INSTR_X, INSTR_X, INSTR_X, INSTR_X, INSTR_X },
   {INSTR_R, INSTR_K, INSTR_X, INSTR_X, INSTR_X, INSTR_X, INSTR_X, INSTR_X },
   {INSTR_R, INSTR_C, INSTR_I1, INSTR_P, INSTR_P, INSTR_P, INSTR_X, INSTR_X },
   {INSTR_R, INSTR_T, INSTR_R, INSTR_P, INSTR_P, INSTR_P, INSTR_X, INSTR_X },
   {INSTR_E, INSTR_T, INSTR_R, INSTR_P, INSTR_P, INSTR_P, INSTR_X, INSTR_X },
   {INSTR_R, INSTR_K, INSTR_R, INSTR_P, INSTR_P, INSTR_P, INSTR_X, INSTR_X },
   {INSTR_P, INSTR_P, INSTR_P, INSTR_MT, INSTR_X, INSTR_X, INSTR_X, INSTR_X },
   {INSTR_P, INSTR_P, INSTR_P, INSTR_L, INSTR_X, INSTR_X, INSTR_X, INSTR_X },
   {INSTR_R, INSTR_P, INSTR_P, INSTR_L, INSTR_X, INSTR_X, INSTR_X, INSTR_X },
   {INSTR_I1, INSTR_P, INSTR_P, INSTR_L, INSTR_X, INSTR_X, INSTR_X, INSTR_X },
   {INSTR_I1, INSTR_P, INSTR_P, INSTR_IT, INSTR_X, INSTR_X, INSTR_X, INSTR_X },
   {INSTR_I1, INSTR_P, INSTR_P, INSTR_HT, INSTR_X, INSTR_X, INSTR_X, INSTR_X },
   {INSTR_R, INSTR_R, INSTR_P, INSTR_S, INSTR_X, INSTR_X, INSTR_X, INSTR_X },
   {INSTR_P, INSTR_C, INSTR_L, INSTR_X, INSTR_X, INSTR_X, INSTR_X, INSTR_X },
   {INSTR_P, INSTR_I1, INSTR_I1, INSTR_L, INSTR_X, INSTR_X, INSTR_X, INSTR_X },
   {INSTR_R, INSTR_C, INSTR_L, INSTR_X, INSTR_X, INSTR_X, INSTR_X, INSTR_X },
   {INSTR_R, INSTR_T, INSTR_L, INSTR_X, INSTR_X, INSTR_X, INSTR_X, INSTR_X },
   {INSTR_E, INSTR_T, INSTR_L, INSTR_X, INSTR_X, INSTR_X, INSTR_X, INSTR_X },
   {INSTR_N, INSTR_P, INSTR_P, INSTR_L, INSTR_L, INSTR_X, INSTR_X, INSTR_X },
   {INSTR_P, INSTR_P, INSTR_P, INSTR_L, INSTR_L, INSTR_L, INSTR_L, INSTR_X },
   {INSTR_R, INSTR_R, INSTR_I1, INSTR_X, INSTR_X, INSTR_X, INSTR_X, INSTR_X },
   {INSTR_R, INSTR_R, INSTR_R, INSTR_I1, INSTR_P, INSTR_P, INSTR_P, INSTR_X },
   {INSTR_R, INSTR_I1, INSTR_P, INSTR_X, INSTR_X, INSTR_X, INSTR_X, INSTR_X },
   {INSTR_E, INSTR_I1, INSTR_P, INSTR_X, INSTR_X, INSTR_X, INSTR_X, INSTR_X },
   {INSTR_R, INSTR_C, INSTR_I1, INSTR_P, INSTR_P, INSTR_P, INSTR_L, INSTR_X },
   {INSTR_R, INSTR_T, INSTR_I1, INSTR_P, INSTR_P, INSTR_P, INSTR_X, INSTR_X },
   {INSTR_E, INSTR_T, INSTR_I1, INSTR_P, INSTR_P, INSTR_P, INSTR_X, INSTR_X },
   {INSTR_R, INSTR_T, INSTR_R, INSTR_I1, INSTR_P, INSTR_P, INSTR_X, INSTR_X },
   {INSTR_E, INSTR_T, INSTR_R, INSTR_I1, INSTR_P, INSTR_P, INSTR_X, INSTR_X },
   {INSTR_I1, INSTR_C, INSTR_P, INSTR_P, INSTR_P, INSTR_P, INSTR_X, INSTR_X },
   {INSTR_I1, INSTR_N, INSTR_P, INSTR_X, INSTR_X, INSTR_X, INSTR_X, INSTR_X },
   {INSTR_I1, INSTR_P, INSTR_P, INSTR_BVT, INSTR_X, INSTR_X, INSTR_X, INSTR_X},
   {INSTR_I1, INSTR_I1, INSTR_P, INSTR_P, INSTR_P, INSTR_P, INSTR_P, INSTR_X },
   {INSTR_I1, INSTR_I1, INSTR_P, INSTR_X, INSTR_X, INSTR_X, INSTR_X, INSTR_X },
   {INSTR_R, INSTR_P, INSTR_P, INSTR_I, INSTR_X, INSTR_X, INSTR_X, INSTR_X },
   {INSTR_R, INSTR_P, INSTR_P, INSTR_F, INSTR_X, INSTR_X, INSTR_X, INSTR_X },
   {INSTR_R, INSTR_P, INSTR_P, INSTR_SL, INSTR_X, INSTR_X, INSTR_X, INSTR_X },
   {INSTR_P, INSTR_P, INSTR_P, INSTR_I, INSTR_X, INSTR_X, INSTR_X, INSTR_X },
   {INSTR_P, INSTR_P, INSTR_P, INSTR_F, INSTR_X, INSTR_X, INSTR_X, INSTR_X },
   {INSTR_P, INSTR_P, INSTR_P, INSTR_SL, INSTR_X, INSTR_X, INSTR_X, INSTR_X }
};

