(****************************************************************************
*Copyright 2008
*  Andrew Gacek, Nathan Guermond, Steven Holte, 
*  Gopalan Nadathur, Xiaochu Qi, Zach Snow
****************************************************************************)
(****************************************************************************
* This file is part of Teyjus.
*
* Teyjus is free software: you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation, either version 3 of the License, or
* (at your option) any later version.
*
* Teyjus is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License
* along with Teyjus.  If not, see <http://www.gnu.org/licenses/>.
****************************************************************************)
(***************************************************************************)
(* The code in this module is in charge of putting out all the information *)
(* generated by the procedures in codegen after a successful processing    *)
(* of a module into in the required bytecode form into a specified byteode *)
(* file.                                                                   *)
(***************************************************************************)

val writeCodeSize : int -> unit
val writeConstInfo : Codegen.cgconsts -> Codegen.cgconsts -> Codegen.cgconsts -> unit
val writeStrings : Codegen.cgstrings -> unit
val writeImpGoalInfo : Codegen.cgimpgoallist -> unit
val writeHashTabInfo : Codegen.cghashtabs -> unit
val writeInstructions : Instr.instruction  list -> unit
  
val writeByteCode : Codegen.cgmodule -> unit
val writeQueryByteCode : Codegen.cgmodule -> unit
