all:
	ocamake *.ml *.mli ../compiler/bytecode.ml ../compiler/bytecode.mli ../compiler/absyn.ml ../compiler/absyn.mli ../compiler/table.ml ../compiler/table.mli ../compiler/symbol.ml ../compiler/symbol.mli ../compiler/option.ml ../compiler/option.mli ../compiler/errormsg.ml ../compiler/errormsg.mli ../compiler/pervasive.ml ../compiler/pervasive.mli ../compiler/pervasiveutils.ml ../compiler/pervasiveutils.mli ../compiler/instr.ml ../compiler/instr.mli -opt -o tjdis

clean:
	rm *.cmx ../compiler/*.cmx